# Generated by Django 5.1.2 on 2024-10-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('tags', models.TextField(null=True)),
            ],
        ),
    ]
